name: Esther Putman, Aerospace Engineer
title: Esther Putman, Aerospace Engineer

# Markdown Processing
markdown: kramdown

# Site Author info
author:
  name             : "Esther Putman"
  avatar           : "profile.png"
  bio              : "Building the future of humans in space"
  location         : "Boulder, CO"
  employer         :
  pubmed           : 
  googlescholar    : # example: "url"
  email            :  "esther.putman@colorado.edu"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  github           : "eputman"
  linkedin         :
  orcid            : 
  twitter          : "@Astro_Esther"

# Defaults

defaults:
  # _about
  - scope:
      path: ""
      type: about
    values:
      layout: default
      author_profile: true
  # _CV
  - scope:
      path: ""
      type: CV
   values:
      layout: default
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: teaching
   values:
      layout: default
      author_profile: true
